"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var nulldot_js_1 = require("nulldot.js");
var encryptor = new nulldot_js_1.NulldotEncryptor();
var originalData = "Hello, Quantum World!";
var key = "SecureKey123";
var encrypted = encryptor.dataToNulldot(originalData, key);
console.log("Encrypted Data:", encrypted);
var decrypted = encryptor.nulldotToData(encrypted, key);
console.log("Decrypted Data:", decrypted);
